repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: master
    hooks:
      - id: go-fumpt
      - id: golangci-lint
      - id: go-test-mod
